name: MatchMaster CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-commits:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Check conventional commits
              uses: cocogitto/cocogitto-action@v3

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install dependencies
              working-directory: ./server
              run: npm install

            - name: Run tests
              working-directory: ./server
              run: npm test